### ISSUE TITLE
Small Room rate caculation for 1 hour and Extra 1 hour

### ISSUE THREAD

**Issue by saifumd-dot** [Muntasir101/Conference-Room-Booking#1]
Description: Select Available Small Room and Available date and time for 1 hour and Extra 1 hour

Steps:
1. Go to Application page.
2. Select Room Type
3. Select Start Date
4. Select Start Time 
5. Select End Data
6. Select End Time
7. Click "Calculate" button

Expected Result: System display Cost is $100+$150=$250

Actual result: ESTIMATED BOOKING COSTS: $200.00 (0 Weeks, 0 Days, 2 Hours)

**Comment by Muntasir101** [comment]
please add screenshot
